#!/usr/bin/env perl
use strict;
use warnings;
use Data::Dumper;
use Net::hostent;

my %outgoing = ();

while (my $message = <>)
{
    chomp $message;

    if ($message =~ m{^error:})
    {
        print "$message\n";
    }
}


exit 0;
